verbose: false
go:
    version: 1.10.3
    cgo: false
repository:
    path: github.com/Percona-Lab/clickhouse_exporter
build:
    prefix: .
    binaries:
        - name: clickhouse_exporter
          path: .
